version: "3.9"

services:
  mysql:
    image: mysql:latest
    container_name: sqlaps
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: teste
      MYSQL_USER: kelsu
      MYSQL_PASSWORD: root123
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql